server:
  port: 8080

# rabbitmq的相关配置
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: root
    virtual-host: /
    # publisher-confirm-type: correlated  # 开启生产者确认机制
    # template:
      # mandatory: true
    # publisher-returns: true